CREATE TABLE [sch_0].[tbl_9]
(
	[STRS_IN_CENSUS_DIVISIONS] [varchar](56) NULL,
	[PG_MILITARY_4GLOBAL] [varchar](250) NULL,
	[SUPUP] [varchar](17) NULL,
	[PG_GLOBAL_4MARKET] [varchar](250) NULL,
	[ODMP_DISP_NAME] [varchar](69) NULL,
	[CS_CHANNEL] [varchar](250) NULL,
	[PG_INTERNAL_MARKET_2CHANNEL] [varchar](250) NULL,
	[STRS_IN_CENSUS_REGIONS] [varchar](23) NULL,
	[CSL_BLK_DT] [date] NULL,
	[MRKT_TT_DMG_CD] [numeric](38, 0) NULL,
	[PG_ARCHIVE_MKT_OPS_1CHANNEL] [varchar](250) NULL,
	[MADRAS_ID] [varchar](250) NULL,
	[CS_MARKET_TYPE] [varchar](250) NULL,
	[WGHT_RULE_NUM] [numeric](38, 0) NULL,
	[PG_ARCHIVE_MKT_OPS_4BANNER] [varchar](250) NULL,
	[WALMART_CMA_REM] [varchar](250) NULL,
	[MRKT_STS_ID] [varchar](14) NULL,
	[NOTES] [varchar](250) NULL,
	[TAGRS] [varchar](14) NULL,
	[PG_MKT_OPS_1CHANNEL] [varchar](250) NULL,
	[PG_GLOBAL_3SUBCHANNEL] [varchar](250) NULL,
	[TOP_CITIES] [varchar](250) NULL,
	[CS_TA_CHANNEL] [varchar](250) NULL,
	[WALMART_CMA] [varchar](250) NULL,
	[XAOC_COMP_MKT_KEY] [numeric](38, 0) NULL,
	[DOMINATE_DMA_NAME] [varchar](14) NULL,
	[PG_CCA_CBA_FORMAT_AGGS] [varchar](250) NULL,
	[PG_AGGREGATE_2TA] [varchar](250) NULL,
	[MRKT_TYP_DTL] [varchar](14) NULL,
	[PG_MKT_OPS_3ACCOUNT] [varchar](250) NULL,
	[TA_REM] [varchar](250) NULL,
	[GEOGRAPHY] [varchar](250) NULL,
	[COMP_KEY] [varchar](14) NULL,
	[CLIENT_ID] [varchar](14) NULL,
	[XAOC_TA_REM] [varchar](250) NULL,
	[MRKT_TYP] [varchar](17) NULL,
	[DMG_CD] [varchar](250) NULL,
	[PRIMARY_MARKET] [varchar](250) NULL,
	[POD_RLS_IND] [varchar](14) NULL,
	[PG_GLOBAL_2CHANNEL] [varchar](250) NULL,
	[CS_MARKET_SET] [varchar](250) NULL,
	[PG_AGG4_3TA] [varchar](250) NULL,
	[PG_ARCHIVE_MKT_OPS_2CST_TEAM] [varchar](250) NULL,
	[TOP_CUSTOMERS] [varchar](250) NULL,
	[COUNTRY] [varchar](14) NULL,
	[WALMART_NON_CMA] [varchar](250) NULL,
	[MRKT_RPTBL_STRT_DT] [varchar](14) NULL,
	[MRKT_HRCH_LVL] [varchar](14) NULL,
	[PG_MILITARY_1WW] [varchar](250) NULL,
	[STRS_IN_STATES] [varchar](38) NULL,
	[SAMS_RSTR_IND] [varchar](14) NULL,
	[PG_AGG4_1MARKETS] [varchar](250) NULL,
	[MARKET_FULFILLMENT_TYPE] [varchar](250) NULL,
	[PG_MILITARY_6MARKET] [varchar](250) NULL,
	[COMP_MRKT_NM] [varchar](65) NULL,
	[MRKT_KEY] [numeric](38, 0) NULL,
	[WALMART_NON_CMA_REM] [varchar](250) NULL,
	[MRKT_DSC_LNG] [varchar](71) NULL,
	[MARRKET_DATA_SOURCE] [varchar](250) NULL,
	[PG_MILITARY_3CUSTOMER] [varchar](250) NULL,
	[LTA_TYPE] [varchar](14) NULL,
	[PG_MKT_OPS_2CUSTOMER_TEAM] [varchar](250) NULL,
	[AOD_MKT_CODE] [varchar](250) NULL,
	[ZGMI_MARKET_TYPE] [varchar](250) NULL,
	[COMP_MRKT_ALL_SINGLE_CHANNEL] [varchar](250) NULL,
	[CHANNEL] [varchar](50) NULL,
	[CS_MARKET_TYPE_SET] [varchar](250) NULL,
	[PG_MKT_OPS_4BANNER] [varchar](250) NULL,
	[ZGMI_HIGHEST_ACCOUNT] [varchar](250) NULL,
	[PG_MILITARY_5MARKET_TTL] [varchar](250) NULL,
	[REPORTABLEYONLY] [varchar](250) NULL,
	[PG_EXTERNALLY_SHAREABLE_AGGS_2] [varchar](250) NULL,
	[ZGMI_LOWEST_ACCOUNT] [varchar](250) NULL,
	[TRADING_AREA_ALL_RETAILERS] [varchar](250) NULL,
	[SHR_MRKT_KEY] [numeric](38, 0) NULL,
	[MRKT_DRILL_IND] [varchar](50) NULL,
	[COMPARATIVE_MARKET_ALL_XAOC] [varchar](250) NULL,
	[SAMPL] [varchar](250) NULL,
	[CS_MARKET_SET_DETAIL] [varchar](250) NULL,
	[MRKT_RSTR_POS] [numeric](38, 0) NULL,
	[ZGMI_SALES_ZONE] [varchar](250) NULL,
	[XAOC_CM_TA_RM_ALL] [varchar](250) NULL,
	[PG_AGGREGATE_1MARKETS] [varchar](250) NULL,
	[MKT_DISP_NAME] [varchar](250) NULL,
	[STR_PL_RSTR] [varchar](50) NULL,
	[MRKT_TYPE_HS] [varchar](50) NULL,
	[COMP_CHNL] [varchar](14) NULL,
	[MRKT_IND] [varchar](50) NULL,
	[XDIM_MRKT2STR] [varchar](250) NULL,
	[MRKT_RPTBL_STOP_DT] [varchar](14) NULL,
	[MRKT_CD] [varchar](14) NULL,
	[MRKT_RSTR_ID] [numeric](38, 0) NULL,
	[PG_INTERNAL_MARKET_1TTL] [varchar](250) NULL,
	[DOMINATE_SMM] [varchar](31) NULL,
	[PRJCTD_IND] [varchar](14) NULL,
	[MRKT_DISP_NAME_FRNT_END] [varchar](250) NULL,
	[STATELINE] [varchar](250) NULL,
	[ZGMI_REGION_GROUPS] [varchar](250) NULL,
	[MARKET_DEFINITION] [varchar](250) NULL,
	[E122] [varchar](250) NULL,
	[PG_INTERNAL_MARKET_3TA] [varchar](250) NULL,
	[ZGMI_CORP_PARENT] [varchar](250) NULL,
	[E321] [varchar](250) NULL,
	[DT_SRC_DTL_NM] [varchar](18) NULL,
	[GO_LIVE_IND] [varchar](250) NULL,
	[PG_EXTERNALLY_SHAREABLE_AGGS] [varchar](250) NULL,
	[CM_TA_RM_ALL] [varchar](250) NULL,
	[LTA_NAME] [varchar](69) NULL,
	[REPORTABLE] [varchar](250) NULL,
	[COMP_MKT] [varchar](250) NULL,
	[CLIENT_SALES_AREAS] [varchar](250) NULL,
	[ACV_ADJ_IND] [numeric](38, 0) NULL,
	[COMP_MKT_KEY] [numeric](38, 0) NULL,
	[PG_MILITARY_2CUSTOMER_TTL] [varchar](250) NULL,
	[MRKT_DSC_SHRT] [varchar](71) NULL,
	[SUPPRESSION] [varchar](15) NULL,
	[DYN_MRKT_FLG] [varchar](250) NULL,
	[PG_AGG4_2TEAMS] [varchar](250) NULL,
	[ZGMI_CHANNEL] [varchar](250) NULL,
	[ETH_MRKT_TYP] [varchar](250) NULL,
	[MARKET_TYPE] [varchar](160) NULL,
	[PG_ARCHIVE_MKT_OPS_3ACCOUNT] [varchar](250) NULL,
	[MRKT_AGG_FLG] [numeric](38, 0) NULL,
	[XAOC_COMP_MKT] [varchar](250) NULL,
	[PG_GLOBAL_1TOTAL] [varchar](250) NULL,
	[DEF_MRKT_FLG] [varchar](250) NULL,
	[OWNER] [varchar](250) NULL
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED INDEX
	(
		[MRKT_KEY] ASC
	)
)